import type { OwnerStats } from "./owner-stats.js";

function escape(value: string): string {
  return value.replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
}
const number = (n: number) => n.toLocaleString("en-US");
function bytes(n: number): string {
  if (n < 1024) return `${number(n)} B`;
  if (n < 1024 ** 2) return `${(n / 1024).toFixed(1)} KiB`;
  if (n < 1024 ** 3) return `${(n / 1024 ** 2).toFixed(1)} MiB`;
  return `${(n / 1024 ** 3).toFixed(2)} GiB`;
}
function date(n: number): string { return new Date(n).toISOString().slice(0, 16).replace("T", " "); }
function tierSource(org: { compTier: string | null; billingTier: string | null }): string {
  if (org.compTier !== null && org.billingTier !== null) return "comp + stripe";
  if (org.compTier !== null) return "comp";
  if (org.billingTier !== null) return "stripe";
  return "none";
}

function page(title: string, content: string, signedIn = false): string {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>${title} · hype-share</title><style>
:root{color-scheme:light;font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#203c36;background:#f4f5ef;font-synthesis:none}
*{box-sizing:border-box}body{margin:0}a{color:inherit;text-underline-offset:4px}button,input{font:inherit}
header{border-bottom:1px solid #dce2d8;background:#fafbf6}nav{max-width:1180px;margin:auto;padding:22px 28px;display:flex;align-items:center;justify-content:space-between;gap:20px}
.brand{font-size:20px;font-weight:750;letter-spacing:-.8px;text-decoration:none}.brand span{color:#6c8176;font-weight:450;margin-left:14px;font-size:13px;letter-spacing:0}
main{max-width:1180px;margin:auto;padding:42px 28px 36px}h1{font-size:clamp(30px,4vw,42px);line-height:1.12;letter-spacing:-1.6px;margin:9px 0 12px;font-weight:650}h2{font-size:18px;letter-spacing:-.4px;margin:0 0 6px}p{line-height:1.6}p.sub{margin:0;color:#63756a;font-size:14px}.eyebrow{text-transform:uppercase;letter-spacing:1.8px;font-size:11px;font-weight:700;color:#698170}
.heading{display:flex;align-items:center;justify-content:space-between;gap:24px;margin-bottom:30px}.actions{display:flex;align-items:center;gap:16px;font-size:13px}
button,.button{display:inline-block;border:1px solid #c8d2c6;background:#fff;color:#203c36;padding:10px 16px;border-radius:7px;font-weight:600;text-decoration:none;cursor:pointer}button:hover,.button:hover{background:#eaf0e5}a:focus-visible,button:focus-visible,input:focus-visible{outline:3px solid #619648;outline-offset:3px}
.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:24px}.card,.panel{background:#fff;border:1px solid #dce2d8;border-radius:12px}.card{padding:23px}.card:first-child{background:#203e34;color:#fff;border-color:#203e34}.label{font-size:13px;color:#627468}.card:first-child .label,.card:first-child .detail{color:#c1d4c4}.value{font-size:34px;letter-spacing:-1.2px;margin:10px 0 7px}.detail{font-size:12px;line-height:1.5;color:#6b7c6f}.grid{display:grid;grid-template-columns:1.7fr 1fr;gap:20px;margin:20px 0}.panel{padding:24px;min-width:0}.panel-head{display:flex;align-items:start;justify-content:space-between;gap:12px}.badge{white-space:nowrap;background:#edf2e7;border-radius:20px;padding:6px 10px;font-size:11px;color:#506843}
.chart{height:160px;display:flex;align-items:end;gap:5px;border-bottom:1px solid #dce2d8;margin-top:24px}.bar{flex:1;background:#709064;min-height:2px;border-radius:3px 3px 0 0}.chart-labels{display:flex;justify-content:space-between;font-size:11px;color:#6b7c6f;margin-top:10px}.legend{margin-top:18px!important}.tier{display:flex;align-items:center;justify-content:space-between;padding:10px 0;border-bottom:1px solid #edf0e9;font-size:13px}.tier:last-child{border:0}.tier-name{display:flex;align-items:center;gap:10px}.dot{width:7px;height:7px;background:#97ac83;border-radius:50%}.notice{display:flex;align-items:center;justify-content:space-between;gap:20px;padding:18px 22px;border:1px solid #d5dfc8;background:#eaf0e0;border-radius:10px;font-size:13px;line-height:1.6}.notice p{margin:0}.table-wrap{overflow-x:auto;margin-top:18px}table{border-collapse:collapse;width:100%;font-size:13px;white-space:nowrap;text-align:left}th{font-size:11px;letter-spacing:.6px;text-transform:uppercase;color:#7a887c;font-weight:500}th,td{padding:13px 12px;border-bottom:1px solid #edf0e9}th:first-child,td:first-child{padding-left:0}td.site{min-width:200px;max-width:280px;white-space:normal;overflow-wrap:anywhere}.site small{display:block;color:#7a887c;margin-top:4px;font-family:ui-monospace,monospace;font-size:11px}.expired{color:#a64631}.empty{text-align:center;padding:35px;color:#6b7c6f;white-space:normal}footer{font-size:12px;color:#7a887c;line-height:1.65;margin-top:24px}.login{max-width:440px;margin:7vh auto 0}.login .panel{padding:32px}.login h1{font-size:32px}.login label{display:block;margin:26px 0 8px;font-size:13px;font-weight:600}.login input{display:block;width:100%;padding:12px;border:1px solid #c5d0c1;border-radius:7px;background:#fbfcf8}.login button{width:100%;margin-top:16px;background:#203e34;color:white;border-color:#203e34}.error{padding:12px;background:#fff1ec;color:#9f3e24;border-radius:6px;font-size:13px}.fine{font-size:12px;color:#6b7c6f;margin-bottom:0}code{font-size:.9em;overflow-wrap:anywhere}
@media(max-width:800px){.metrics{grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:1fr}.heading{align-items:start}.actions{flex-wrap:wrap}.brand span{display:none}main{padding:28px 18px}nav{padding:18px}.card{padding:18px}.value{font-size:29px}.panel{padding:18px}.notice{display:block}.heading .button{white-space:nowrap}.chart{gap:3px}}
@media(max-width:420px){.heading{display:block}.heading .actions{margin-top:18px}.login .panel{padding:24px}.metrics{gap:10px}}
</style></head><body><header><nav><a class="brand" href="/owner">hype-share<span>Owner portal</span></a>${signedIn ? '<form method="post" action="/owner/logout"><button type="submit">Sign out</button></form>' : '<a href="/">Back to home</a>'}</nav></header><main>${content}</main></body></html>`;
}

export function loginPage(error?: string): string {
  return page("Owner login", `<div class="login"><div class="panel"><div class="eyebrow">Owner access</div><h1>Your service,<br>at a glance.</h1><p class="sub">Sign in to see accounts, publishing activity, and storage across hype-share.</p>${error ? `<p class="error" role="alert">${escape(error)}</p>` : ""}<form method="post" action="/owner/login"><label for="token">Owner token</label><input id="token" name="token" type="password" autocomplete="current-password" required maxlength="2048" autofocus><button type="submit">Sign in</button></form><p class="fine">Use the server's <code>SHAREPLAN_ADMIN_TOKEN</code>. Your session lasts eight hours.</p></div></div>`);
}

export function dashboardPage(stats: OwnerStats): string {
  const { accounts, sites, versions, orgs } = stats;
  const publishes = stats.activity.reduce((sum, day) => sum + day.publishes, 0);
  const peak = Math.max(1, ...stats.activity.map(day => day.publishes));
  const claimedPercent = accounts.customers ? Math.round(accounts.claimed / accounts.customers * 100) : 0;
  const cards = [
    ["Active sites", number(sites.active), `${number(sites.total)} total · ${number(sites.expired)} expired`],
    ["Customer accounts", number(accounts.customers), `${number(accounts.claimed)} claimed · ${claimedPercent}% claim rate`],
    ["Publishes · 30 days", number(publishes), "UTC calendar days · surviving site history"],
    ["Retained file size", bytes(versions.retainedBytes), `${number(versions.retained)} versions · metadata estimate`],
  ];
  const now = Date.parse(stats.generatedAt);
  return page("Overview", `<div class="heading"><div><div class="eyebrow">Service overview</div><h1>A home for every share.</h1><p class="sub">Accounts, content, and activity across your service.</p></div><div class="actions"><a href="/api/v1/admin/stats">View JSON</a><a class="button" href="/owner">Refresh</a></div></div>
<section class="metrics" aria-label="Service totals">${cards.map(([label, value, detail]) => `<div class="card"><div class="label">${label}</div><div class="value">${value}</div><div class="detail">${detail}</div></div>`).join("")}</section>
<div class="notice"><p><strong>${number(sites.expiringNext7Days)} sites expire in the next 7 days.</strong> ${sites.expiringNext7Days ? "Review recent sites below to spot content nearing expiry." : "No upcoming expirations in that window."}</p><span>${number(sites.permanent)} permanent ${sites.permanent === 1 ? "site" : "sites"}</span></div>
<div class="grid"><section class="panel"><div class="panel-head"><div><h2>Publishing activity</h2><p class="sub">New versions across the last 30 days</p></div><span class="badge">${number(publishes)} publishes</span></div><div class="chart" role="img" aria-label="${number(publishes)} publishes across the last 30 UTC days">${stats.activity.map(day => `<div class="bar" style="height:${Math.max(1, day.publishes / peak * 100)}%" title="${day.date}: ${day.publishes} publishes"></div>`).join("")}</div><div class="chart-labels"><span>${stats.activity[0]!.date}</span><span>${stats.activity[29]!.date}</span></div>${publishes === 0 ? '<p class="sub legend">Publish your first site to start seeing activity here.</p>' : ''}<details class="fine"><summary>Daily counts</summary><div class="table-wrap"><table><thead><tr><th scope="col">Date (UTC)</th><th scope="col">Publishes</th></tr></thead><tbody>${stats.activity.map(day => `<tr><td>${day.date}</td><td>${number(day.publishes)}</td></tr>`).join("")}</tbody></table></div></details></section>
<section class="panel"><div class="panel-head"><div><h2>Accounts by tier</h2><p class="sub">${number(accounts.total)} ${accounts.total === 1 ? "account" : "accounts"} · ${number(stats.keys.active)} active API ${stats.keys.active === 1 ? "key" : "keys"} · ${number(accounts.inOrg)} in organizations · ${number(orgs.elevated)} inherit a higher tier from an org</p></div></div>${stats.tiers.map(tier => `<div class="tier"><span class="tier-name"><span class="dot"></span>${escape(tier.tier === "ops" ? "Operator" : tier.tier)}</span><strong>${number(tier.count)}</strong></div>`).join("")}<p class="sub legend">Counts are own tiers; organization members publish at the higher of own and organization tier.</p></section></div>
<section class="panel"><div class="panel-head"><div><h2>Recent sites</h2><p class="sub">20 most recently updated · all times UTC</p></div><span class="badge">${bytes(sites.currentBytes)} current files</span></div><div class="table-wrap"><table><thead><tr><th scope="col">Site</th><th scope="col">Visibility</th><th scope="col">Size</th><th scope="col">Updated</th><th scope="col">Expires</th></tr></thead><tbody>${stats.recentSites.length ? stats.recentSites.map(site => `<tr><td class="site">${escape(site.title || "Untitled site")}<small>${escape(site.id)}</small></td><td>${escape(site.visibility)}</td><td>${bytes(site.byteSize)}</td><td>${date(site.updatedAt)}</td><td${site.expiresAt !== null && site.expiresAt <= now ? ' class="expired"' : ''}>${site.expiresAt === null ? "Permanent" : `${date(site.expiresAt)}${site.expiresAt <= now ? " · expired" : ""}`}</td></tr>`).join("") : '<tr><td colspan="5" class="empty">No sites yet. Sites appear here after their first successful publish.</td></tr>'}</tbody></table></div></section>
<section class="panel"><div class="panel-head"><div><h2>Organizations</h2><p class="sub">${number(orgs.total)} ${orgs.total === 1 ? "organization" : "organizations"} · ${number(orgs.members)} ${orgs.members === 1 ? "member" : "members"} · ${number(orgs.joinEnabled)} accepting joins</p></div>${orgs.total > stats.orgList.length ? `<span class="badge">${number(stats.orgList.length)} largest shown</span>` : ""}</div><div class="table-wrap"><table><thead><tr><th scope="col">Org</th><th scope="col">Tier</th><th scope="col">Members</th><th scope="col">Sites</th><th scope="col">Permanent</th><th scope="col">Pool</th><th scope="col">Join</th><th scope="col">Since</th></tr></thead><tbody>${stats.orgList.length ? stats.orgList.map(org => `<tr><td class="site">${escape(org.name)}<small>${escape(org.id)}</small></td><td>${escape(org.tier ?? "none")} <span class="badge">${tierSource(org)}</span></td><td>${number(org.members)}/${number(org.maxMembers)}</td><td>${number(org.sites)}</td><td>${number(org.permanent)}</td><td>${org.publishPerHour === null ? "tier default" : `${number(org.publishPerHour)}/h`}</td><td>${org.joinEnabled ? "on" : "off"}</td><td>${date(org.createdAt)}</td></tr>`).join("") : '<tr><td colspan="8" class="empty">No organizations yet. Create one with <code>shareplan create-org</code>.</td></tr>'}</tbody></table></div></section>
<footer>Updated ${date(now)} UTC. Figures come from current database records. Deleted sites and their publishing history are excluded. Retained file size estimates stored version content, including expired sites awaiting cleanup; it is not an S3 billing total. Page views, visitors, bandwidth, and revenue are not tracked yet. Organization tier is the higher of the operator comp and the billing tier; member sites are clamped when it drops. Tiers are changed with the admin token, not here.</footer>`, true);
}
